language: node_js
node_js:
  - 11.6.0
cache: npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: gae
  keyfile: gae.json
  project: pro-bruin-207112
  default: true
  on: master
  verbosity: debug
before_install:
  - openssl aes-256-cbc -K $encrypted_9d860c284d98_key -iv $encrypted_9d860c284d98_iv
    -in gae.json.enc -out gae.json -d
