language: node_js
node_js:
  - 11.6.0
cache: npm
install:
  - npm install
script:
  - npm run build
deploy:
  provider: gae
  keyfile: gae.json
  project: pro-bruin-207112
  default: true
  on: master
  verbosity: debug
