language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: gae
  keyfile: gae.json
  project: pro-bruin-207112
  default: true
  on:
    branch: master
  verbosity: debug
before_install:
  - openssl aes-256-cbc -K $encrypted_77f0ab6568aa_key -iv $encrypted_77f0ab6568aa_iv
    -in gae.json.enc -out gae.json -d
